import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Register a font (optional — uses default)
Font.register({
  family: 'Helvetica',
  fonts: [
    { src: 'Helvetica' },
    { src: 'Helvetica-Bold', fontWeight: 700 }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 8,
    color: '#1a1a2e',
  },
  category: {
    fontSize: 12,
    color: '#7c3aed',
    marginBottom: 12,
    fontWeight: 500,
  },
  date: {
    fontSize: 10,
    color: '#888888',
    marginBottom: 16,
  },
  scripture: {
    fontSize: 13,
    fontStyle: 'italic',
    color: '#4f46e5',
    marginBottom: 16,
    padding: 10,
    backgroundColor: '#f5f3ff',
    borderRadius: 6,
  },
  story: {
    fontSize: 12,
    lineHeight: 1.7,
    color: '#333333',
    marginBottom: 16,
  },
  prayerTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#7c3aed',
    marginBottom: 4,
  },
  prayer: {
    fontSize: 12,
    fontStyle: 'italic',
    color: '#555555',
    lineHeight: 1.6,
    padding: 10,
    backgroundColor: '#fafafa',
    borderRadius: 6,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#aaaaaa',
    textAlign: 'center',
  },
});

export function createDevotionPDF(devotion) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{devotion.title}</Text>
        <Text style={styles.category}>✦ {devotion.category || 'Faith'}</Text>
        <Text style={styles.date}>{devotion.date || new Date().toLocaleDateString()}</Text>
        
        <Text style={styles.scripture}>{devotion.scripture}</Text>
        
        <Text style={styles.story}>{devotion.story}</Text>
        
        <Text style={styles.prayerTitle}>🙏 Prayer</Text>
        <Text style={styles.prayer}>{devotion.prayer}</Text>
        
        <Text style={styles.footer}>Generated by Bible Studier • Daily Devotional</Text>
      </Page>
    </Document>
  );
}